IDS:
  - BulkM1_CCP2LANXX_TCTCTACT-CGCGGTTC_L004_R1
  - BulkM2_CCP2LANXX_ATGTAAGT-ACTCTATG_L004_R1
  - BulkM3_CCP2LANXX_CTTGGTAT-CCAAGTCC_L004_R1
  - BulkM4_CCP2LANXX_AGCCTCAT-AGTAGAGA_L004_R1
  - SingleCellM1_CCP2LANXX_TGGCCGGT-TAGAGCGC_L004_R1
  - SingleCellM2_CCP2LANXX_GGTCACGA-GTATTATG_L004_R1
  - SingleCellM3_CCP2LANXX_CGCTATGT-TCCGACAC_L004_R1
  - SingleCellM4_CCP2LANXX_GGACTTGG-CGCAGACG_L004_R1